CREATE TABLE "configuracoes" (
  "empresaId" UUID PRIMARY KEY REFERENCES "empresas"("id"),
  "permitirAutoConferencia" BOOLEAN NOT NULL DEFAULT false,
  "permitirAprovacaoExcepcionalDivergencia" BOOLEAN NOT NULL DEFAULT false,
  "razaoSocial" TEXT NOT NULL DEFAULT '',
  "nomeFantasia" TEXT,
  "cnpj" TEXT NOT NULL DEFAULT '',
  "email" TEXT,
  "telefone" TEXT,
  "enderecoLogradouro" TEXT,
  "enderecoNumero" TEXT,
  "enderecoBairro" TEXT,
  "enderecoCidade" TEXT,
  "enderecoUf" TEXT,
  "enderecoCep" TEXT,
  "depositoNome" TEXT NOT NULL DEFAULT '',
  "depositoLogradouro" TEXT NOT NULL DEFAULT '',
  "depositoNumero" TEXT NOT NULL DEFAULT '',
  "depositoBairro" TEXT NOT NULL DEFAULT '',
  "depositoCidade" TEXT NOT NULL DEFAULT '',
  "depositoUf" TEXT NOT NULL DEFAULT '',
  "depositoCep" TEXT NOT NULL DEFAULT '',
  "depositoResponsavel" TEXT,
  "tempoExpiracaoSessaoMinutos" INTEGER NOT NULL DEFAULT 30,
  "politicaSenhaMinima" TEXT NOT NULL DEFAULT 'MEDIA',
  "duracaoSenhaTemporariaDias" INTEGER NOT NULL DEFAULT 7,
  "updatedAt" TIMESTAMP(3) NOT NULL
);