import type { Pedido } from "@/types/domain"

const VENDEDOR_1 = "usr-001"
const VENDEDOR_2 = "usr-002"
const SUPERVISOR_1 = "usr-003"

export const MOCK_PEDIDOS: Pedido[] = [
    {
        id: "ped-001",
        numero: 1001,
        clienteId: "cli-001",
        vendedorId: VENDEDOR_1,
        endereco: {
            enderecoId: "end-1",
            logradouro: "Av. Industrial",
            numero: "1420",
            bairro: "Distrito Industrial",
            cidade: "Caxias do Sul",
            uf: "RS",
            cep: "95050-000",
        },
        itens: [
            {
                id: "item-001",
                produtoId: "prd-002",
                quantidade: 2,
                precoUnitario: 329.0,
                desconto: 0,
                status: "PENDENTE_ESTOQUE",
            },
        ],
        status: "CRIADO",
        pendencia: "NENHUMA",
        valorTotal: 658.0,
        criadoEm: "2026-07-01T09:12:00-03:00",
        statusAlteradoEm: "2026-07-01T09:12:00-03:00",
        eventos: [
            {
                id: "evt-001",
                tipo: "PEDIDO_CRIADO",
                descricao: "Pedido criado, sem estoque suficiente para nenhum item.",
                dataHora: "2026-07-01T09:12:00-03:00",
                usuarioId: VENDEDOR_1,
            },
        ],
    },
    {
        id: "ped-002",
        numero: 1002,
        clienteId: "cli-002",
        vendedorId: VENDEDOR_1,
        endereco: {
            enderecoId: "end-3",
            logradouro: "Rua do Comércio",
            numero: "305",
            bairro: "Centro",
            cidade: "Vitória",
            uf: "ES",
            cep: "29010-000",
        },
        itens: [
            {
                id: "item-002",
                produtoId: "prd-001",
                quantidade: 1,
                precoUnitario: 189.9,
                desconto: 0,
                status: "PENDENTE",
            },
            {
                id: "item-003",
                produtoId: "prd-003",
                quantidade: 15.5,
                precoUnitario: 8.75,
                desconto: 5,
                status: "PENDENTE",
            },
        ],
        status: "RESERVADO",
        pendencia: "NENHUMA",
        valorTotal: 318.53,
        criadoEm: "2026-07-02T10:30:00-03:00",
        statusAlteradoEm: "2026-07-02T10:30:00-03:00",
        eventos: [
            {
                id: "evt-002",
                tipo: "PEDIDO_CRIADO",
                descricao: "Pedido criado.",
                dataHora: "2026-07-02T10:30:00-03:00",
                usuarioId: VENDEDOR_1,
            },
            {
                id: "evt-003",
                tipo: "ESTOQUE_RESERVADO",
                descricao: "Reserva de todos os itens concluída com sucesso.",
                dataHora: "2026-07-02T10:30:05-03:00",
                usuarioId: VENDEDOR_1,
            },
        ],
    },
    {
        id: "ped-003",
        numero: 1003,
        clienteId: "cli-004",
        vendedorId: VENDEDOR_2,
        endereco: {
            enderecoId: "end-5",
            logradouro: "Rodovia BR-316, km 8",
            numero: "s/n",
            bairro: "Coqueiro",
            cidade: "Ananindeua",
            uf: "PA",
            cep: "67130-000",
        },
        itens: [
            {
                id: "item-004",
                produtoId: "prd-005",
                quantidade: 50,
                precoUnitario: 6.9,
                desconto: 0,
                status: "PENDENTE",
            },
            {
                id: "item-005",
                produtoId: "prd-007",
                quantidade: 30,
                precoUnitario: 9.9,
                desconto: 0,
                status: "PENDENTE_ESTOQUE",
            },
        ],
        status: "RESERVADO",
        pendencia: "NENHUMA",
        valorTotal: 642.0,
        criadoEm: "2026-07-03T14:05:00-03:00",
        statusAlteradoEm: "2026-07-03T14:05:00-03:00",
        eventos: [
            {
                id: "evt-004",
                tipo: "PEDIDO_CRIADO",
                descricao: "Pedido criado.",
                dataHora: "2026-07-03T14:05:00-03:00",
                usuarioId: VENDEDOR_2,
            },
            {
                id: "evt-005",
                tipo: "ESTOQUE_RESERVADO",
                descricao: "Reserva parcial — 1 item sem estoque suficiente.",
                dataHora: "2026-07-03T14:05:04-03:00",
                usuarioId: VENDEDOR_2,
            },
        ],
    },
    {
        id: "ped-004",
        numero: 1004,
        clienteId: "cli-005",
        vendedorId: VENDEDOR_1,
        endereco: {
            enderecoId: "end-6",
            logradouro: "Alameda das Palmeiras",
            numero: "77",
            bairro: "Jardim América",
            cidade: "Goiânia",
            uf: "GO",
            cep: "74815-320",
        },
        itens: [
            {
                id: "item-006",
                produtoId: "prd-002",
                quantidade: 1,
                precoUnitario: 329.0,
                desconto: 0,
                status: "SEPARADO",
            },
            {
                id: "item-007",
                produtoId: "prd-003",
                quantidade: 8,
                precoUnitario: 8.75,
                desconto: 0,
                status: "PENDENTE",
            },
        ],
        status: "EM_SEPARACAO",
        pendencia: "NENHUMA",
        valorTotal: 399.0,
        criadoEm: "2026-07-04T08:20:00-03:00",
        statusAlteradoEm: "2026-07-05T07:40:00-03:00",
        eventos: [
            {
                id: "evt-006",
                tipo: "PEDIDO_CRIADO",
                descricao: "Pedido criado.",
                dataHora: "2026-07-04T08:20:00-03:00",
                usuarioId: VENDEDOR_1,
            },
            {
                id: "evt-007",
                tipo: "ESTOQUE_RESERVADO",
                descricao: "Reserva de todos os itens concluída com sucesso.",
                dataHora: "2026-07-04T08:20:03-03:00",
                usuarioId: VENDEDOR_1,
            },
            {
                id: "evt-008",
                tipo: "SEPARACAO_INICIADA",
                descricao: "Separação iniciada pelo estoquista.",
                dataHora: "2026-07-05T07:40:00-03:00",
                usuarioId: "usr-004",
            },
        ],
    },
    {
        id: "ped-005",
        numero: 1005,
        clienteId: "cli-007",
        vendedorId: VENDEDOR_2,
        endereco: {
            enderecoId: "end-8",
            logradouro: "Av. Beira Mar",
            numero: "1200",
            bairro: "Praia Grande",
            cidade: "Florianópolis",
            uf: "SC",
            cep: "88015-700",
        },
        itens: [
            {
                id: "item-008",
                produtoId: "prd-001",
                quantidade: 2,
                precoUnitario: 189.9,
                desconto: 0,
                status: "SEPARADO",
            },
            {
                id: "item-009",
                produtoId: "prd-005",
                quantidade: 200,
                precoUnitario: 6.9,
                desconto: 0,
                status: "PENDENTE_ESTOQUE",
            },
        ],
        status: "EM_SEPARACAO",
        pendencia: "RUPTURA_ESTOQUE",
        valorTotal: 1759.8,
        criadoEm: "2026-07-05T11:00:00-03:00",
        statusAlteradoEm: "2026-07-06T09:15:00-03:00",
        eventos: [
            {
                id: "evt-009",
                tipo: "PEDIDO_CRIADO",
                descricao: "Pedido criado.",
                dataHora: "2026-07-05T11:00:00-03:00",
                usuarioId: VENDEDOR_2,
            },
            {
                id: "evt-010",
                tipo: "ESTOQUE_RESERVADO",
                descricao: "Reserva de todos os itens concluída com sucesso.",
                dataHora: "2026-07-05T11:00:03-03:00",
                usuarioId: VENDEDOR_2,
            },
            {
                id: "evt-011",
                tipo: "SEPARACAO_INICIADA",
                descricao: "Separação iniciada pelo estoquista.",
                dataHora: "2026-07-06T09:00:00-03:00",
                usuarioId: "usr-004",
            },
            {
                id: "evt-012",
                tipo: "RUPTURA_ESTOQUE_DETECTADA",
                descricao: "Divergência entre saldo reservado e físico disponível no item de vergalhão. Aguardando decisão do supervisor.",
                dataHora: "2026-07-06T09:15:00-03:00",
                usuarioId: "usr-004",
            },
        ],
    },
    {
        id: "ped-006",
        numero: 1006,
        clienteId: "cli-008",
        vendedorId: VENDEDOR_1,
        endereco: {
            enderecoId: "end-9",
            logradouro: "Rua Projetada A",
            numero: "15",
            bairro: "Parque Industrial",
            cidade: "Sorocaba",
            uf: "SP",
            cep: "18085-000",
        },
        itens: [
            {
                id: "item-010",
                produtoId: "prd-006",
                quantidade: 20,
                precoUnitario: 12.3,
                desconto: 0,
                status: "SEPARADO",
            },
            {
                id: "item-011",
                produtoId: "prd-007",
                quantidade: 10,
                precoUnitario: 9.9,
                desconto: 0,
                status: "SEPARADO",
            },
        ],
        status: "EM_CONFERENCIA",
        pendencia: "NENHUMA",
        valorTotal: 345.0,
        criadoEm: "2026-07-02T13:00:00-03:00",
        statusAlteradoEm: "2026-07-04T10:00:00-03:00",
        eventos: [
            {
                id: "evt-013",
                tipo: "PEDIDO_CRIADO",
                descricao: "Pedido criado.",
                dataHora: "2026-07-02T13:00:00-03:00",
                usuarioId: VENDEDOR_1,
            },
            {
                id: "evt-014",
                tipo: "ESTOQUE_RESERVADO",
                descricao: "Reserva de todos os itens concluída com sucesso.",
                dataHora: "2026-07-02T13:00:03-03:00",
                usuarioId: VENDEDOR_1,
            },
            {
                id: "evt-015",
                tipo: "SEPARACAO_CONCLUIDA",
                descricao: "Todos os itens separados sem divergência.",
                dataHora: "2026-07-03T15:30:00-03:00",
                usuarioId: "usr-004",
            },
            {
                id: "evt-016",
                tipo: "CONFERENCIA_INICIADA",
                descricao: "Conferência iniciada.",
                dataHora: "2026-07-04T10:00:00-03:00",
                usuarioId: "usr-005",
            },
        ],
    },
    {
        id: "ped-007",
        numero: 1007,
        clienteId: "cli-001",
        vendedorId: VENDEDOR_2,
        endereco: {
            enderecoId: "end-2",
            logradouro: "Rua das Oficinas",
            numero: "88",
            bairro: "São Ciro",
            cidade: "Caxias do Sul",
            uf: "RS",
            cep: "95040-100",
        },
        itens: [
            {
                id: "item-012",
                produtoId: "prd-003",
                quantidade: 40,
                precoUnitario: 8.75,
                desconto: 0,
                status: "SEPARADO",
            },
        ],
        status: "EM_CONFERENCIA",
        pendencia: "DIVERGENCIA_CONFERENCIA",
        valorTotal: 350.0,
        criadoEm: "2026-07-01T16:00:00-03:00",
        statusAlteradoEm: "2026-07-03T11:20:00-03:00",
        eventos: [
            {
                id: "evt-017",
                tipo: "PEDIDO_CRIADO",
                descricao: "Pedido criado.",
                dataHora: "2026-07-01T16:00:00-03:00",
                usuarioId: VENDEDOR_2,
            },
            {
                id: "evt-018",
                tipo: "ESTOQUE_RESERVADO",
                descricao: "Reserva de todos os itens concluída com sucesso.",
                dataHora: "2026-07-01T16:00:03-03:00",
                usuarioId: VENDEDOR_2,
            },
            {
                id: "evt-019",
                tipo: "SEPARACAO_CONCLUIDA",
                descricao: "Todos os itens separados.",
                dataHora: "2026-07-02T14:00:00-03:00",
                usuarioId: "usr-004",
            },
            {
                id: "evt-020",
                tipo: "CONFERENCIA_INICIADA",
                descricao: "Conferência iniciada.",
                dataHora: "2026-07-03T11:00:00-03:00",
                usuarioId: "usr-005",
            },
            {
                id: "evt-021",
                tipo: "DIVERGENCIA_DETECTADA",
                descricao: "Quantidade conferida diverge da separada. Aguardando decisão do supervisor.",
                dataHora: "2026-07-03T11:20:00-03:00",
                usuarioId: "usr-005",
            },
        ],
    },
    {
        id: "ped-008",
        numero: 1008,
        clienteId: "cli-002",
        vendedorId: VENDEDOR_1,
        endereco: {
            enderecoId: "end-3",
            logradouro: "Rua do Comércio",
            numero: "305",
            bairro: "Centro",
            cidade: "Vitória",
            uf: "ES",
            cep: "29010-000",
        },
        itens: [
            {
                id: "item-013",
                produtoId: "prd-001",
                quantidade: 3,
                precoUnitario: 189.9,
                desconto: 10,
                status: "SEPARADO",
            },
        ],
        status: "CONFERIDO",
        pendencia: "NENHUMA",
        valorTotal: 512.73,
        criadoEm: "2026-06-28T09:00:00-03:00",
        statusAlteradoEm: "2026-06-30T16:45:00-03:00",
        eventos: [
            {
                id: "evt-022",
                tipo: "PEDIDO_CRIADO",
                descricao: "Pedido criado.",
                dataHora: "2026-06-28T09:00:00-03:00",
                usuarioId: VENDEDOR_1,
            },
            {
                id: "evt-023",
                tipo: "ESTOQUE_RESERVADO",
                descricao: "Reserva concluída com sucesso.",
                dataHora: "2026-06-28T09:00:03-03:00",
                usuarioId: VENDEDOR_1,
            },
            {
                id: "evt-024",
                tipo: "SEPARACAO_CONCLUIDA",
                descricao: "Separação concluída sem divergência.",
                dataHora: "2026-06-29T13:10:00-03:00",
                usuarioId: "usr-004",
            },
            {
                id: "evt-025",
                tipo: "CONFERENCIA_CONCLUIDA",
                descricao: "Conferência concluída sem divergência.",
                dataHora: "2026-06-30T16:45:00-03:00",
                usuarioId: "usr-005",
            },
        ],
    },
    {
        id: "ped-009",
        numero: 1009,
        clienteId: "cli-004",
        vendedorId: VENDEDOR_2,
        endereco: {
            enderecoId: "end-5",
            logradouro: "Rodovia BR-316, km 8",
            numero: "s/n",
            bairro: "Coqueiro",
            cidade: "Ananindeua",
            uf: "PA",
            cep: "67130-000",
        },
        itens: [
            {
                id: "item-014",
                produtoId: "prd-006",
                quantidade: 15,
                precoUnitario: 12.3,
                desconto: 0,
                status: "SEPARADO",
            },
        ],
        status: "EXPEDIDO",
        pendencia: "NENHUMA",
        transportadora: "Transportes Rápido Norte",
        valorTotal: 184.5,
        criadoEm: "2026-06-25T10:00:00-03:00",
        statusAlteradoEm: "2026-06-29T08:30:00-03:00",
        eventos: [
            {
                id: "evt-026",
                tipo: "PEDIDO_CRIADO",
                descricao: "Pedido criado.",
                dataHora: "2026-06-25T10:00:00-03:00",
                usuarioId: VENDEDOR_2,
            },
            {
                id: "evt-027",
                tipo: "ESTOQUE_RESERVADO",
                descricao: "Reserva concluída com sucesso.",
                dataHora: "2026-06-25T10:00:03-03:00",
                usuarioId: VENDEDOR_2,
            },
            {
                id: "evt-028",
                tipo: "SEPARACAO_CONCLUIDA",
                descricao: "Separação concluída sem divergência.",
                dataHora: "2026-06-26T14:00:00-03:00",
                usuarioId: "usr-004",
            },
            {
                id: "evt-029",
                tipo: "CONFERENCIA_CONCLUIDA",
                descricao: "Conferência concluída sem divergência.",
                dataHora: "2026-06-27T09:00:00-03:00",
                usuarioId: "usr-005",
            },
            {
                id: "evt-030",
                tipo: "PEDIDO_EXPEDIDO",
                descricao: "Mercadoria despachada. Baixa física de estoque efetivada.",
                dataHora: "2026-06-29T08:30:00-03:00",
                usuarioId: "usr-006",
            },
        ],
    },
    {
        id: "ped-010",
        numero: 1010,
        clienteId: "cli-005",
        vendedorId: VENDEDOR_1,
        endereco: {
            enderecoId: "end-6",
            logradouro: "Alameda das Palmeiras",
            numero: "77",
            bairro: "Jardim América",
            cidade: "Goiânia",
            uf: "GO",
            cep: "74815-320",
        },
        itens: [
            {
                id: "item-015",
                produtoId: "prd-007",
                quantidade: 25,
                precoUnitario: 9.9,
                desconto: 0,
                status: "SEPARADO",
            },
        ],
        status: "ENTREGUE",
        pendencia: "NENHUMA",
        transportadora: "Log Express SC",
        valorTotal: 247.5,
        criadoEm: "2026-06-18T09:00:00-03:00",
        statusAlteradoEm: "2026-06-23T17:00:00-03:00",
        eventos: [
            {
                id: "evt-031",
                tipo: "PEDIDO_CRIADO",
                descricao: "Pedido criado.",
                dataHora: "2026-06-18T09:00:00-03:00",
                usuarioId: VENDEDOR_1,
            },
            {
                id: "evt-032",
                tipo: "ESTOQUE_RESERVADO",
                descricao: "Reserva concluída com sucesso.",
                dataHora: "2026-06-18T09:00:03-03:00",
                usuarioId: VENDEDOR_1,
            },
            {
                id: "evt-033",
                tipo: "PEDIDO_EXPEDIDO",
                descricao: "Mercadoria despachada.",
                dataHora: "2026-06-20T08:00:00-03:00",
                usuarioId: "usr-006",
            },
            {
                id: "evt-034",
                tipo: "PEDIDO_ENTREGUE",
                descricao: "Entrega confirmada.",
                dataHora: "2026-06-23T17:00:00-03:00",
                usuarioId: "usr-006",
            },
        ],
    },
    {
        id: "ped-011",
        numero: 1011,
        clienteId: "cli-007",
        vendedorId: VENDEDOR_2,
        endereco: {
            enderecoId: "end-8",
            logradouro: "Av. Beira Mar",
            numero: "1200",
            bairro: "Praia Grande",
            cidade: "Florianópolis",
            uf: "SC",
            cep: "88015-700",
        },
        itens: [
            {
                id: "item-016",
                produtoId: "prd-002",
                quantidade: 1,
                precoUnitario: 329.0,
                desconto: 0,
                status: "CANCELADO",
            },
        ],
        status: "CANCELADO",
        pendencia: "NENHUMA",
        valorTotal: 329.0,
        criadoEm: "2026-07-06T15:00:00-03:00",
        statusAlteradoEm: "2026-07-07T09:00:00-03:00",
        motivoCancelamento: "Cliente desistiu da compra após confirmar disponibilidade de outro fornecedor.",
        eventos: [
            {
                id: "evt-035",
                tipo: "PEDIDO_CRIADO",
                descricao: "Pedido criado.",
                dataHora: "2026-07-06T15:00:00-03:00",
                usuarioId: VENDEDOR_2,
            },
            {
                id: "evt-036",
                tipo: "ESTOQUE_RESERVADO",
                descricao: "Reserva concluída com sucesso.",
                dataHora: "2026-07-06T15:00:03-03:00",
                usuarioId: VENDEDOR_2,
            },
            {
                id: "evt-037",
                tipo: "PEDIDO_CANCELADO",
                descricao: "Cliente desistiu da compra após confirmar disponibilidade de outro fornecedor.",
                dataHora: "2026-07-07T09:00:00-03:00",
                usuarioId: VENDEDOR_2,
            },
        ],
    },
]
